- name: Deploy Image
  hosts: all
  remote_user: root
  become: true

  tasks:
  - name: Install Openssh Client
    ansible.builtin.apt:
      name: openssh-client

  - name: Clone Source Code
    args:
      chdir: /home/demo/github
    ansible.builtin.command:
      cmd: git clone https://github.com/covernetwork/semaphore-test.git .

  - name: Deploy Image From Source Code
    args:
      chdir: /home/demo/github/semaphore-test/web
    ansible.builtin.command:
      cmd: docker build -t demo-webapp
