- name: Deploy Image
  hosts: all
  remote_user: root
  become: true

  tasks:
  - name: Install Openssh Client
    ansible.builtin.apt:
      name: openssh-client

  - name: Clone Source Code
    args:
      chdir: /home/demo/github
    ansible.builtin.command:
      cmd: git pull https://github.com/covernetwork/semaphore-test.git

  - name: Deploy Image From Source Code
    args:
      chdir: /home/demo/github/web
    ansible.builtin.command:
      cmd: docker build -t demo-webapp .

  - name: Create Service
    ansible.builtin.command:
      cmd: docker service create --name demo-webapp --publish 4000:3000 demo-webapp
