- name: Deploy Image
  hosts: all
  remote_user: root
  become: true

  tasks:
  - name: Clone Source Code
    ansible.builtin.command:
      argv:
      - git clone
      - '{{ http_clone }}'
      - /home/demo/github

  - name: Deploy Image From Source Code
    ansible.builtin.command:
      argv:
      - docker build -t demo-webapp
      - /home/demo/github/semaphore-test/web
