- name: Deploy Image
  hosts: all
  remote_user: root
  become: true

  tasks:
  - name: Clone Source Code
    ansible.builtin.command:
      args:
        chdir: /home/demo/github
      argv:
      - git clone
      - '{{ http_clone }}'

  - name: Deploy Image From Source Code
    ansible.builtin.command:
      args:
        chdir: /home/demo/github/semaphore-test/web
      argv:
      - docker build -t demo-webapp
