# Install python and docker
- name: Install Python and Docker
  hosts: all
  remote_user: root
  become: true

  tasks:
  - name: install python package manager
    apt:
      name: python3-pip

  - name: "Provide custom input"
    ansible.builtin.expect:
      command: 'launch.sh'
      responses:
        'Do you want to continue\"\[Y\/N\]\"': 'y'

  - name: install python sdk
    become_user: root
    pip:
      name:
      - docker
      - docker-compose
