# Install python and docker
- name: Install Python and Docker
  hosts: all
  remote_user: root
  become: true

  tasks:
  - name: Multiple questions with responses
    ansible.builtin.expect:
    command: launch.sh
    responses:
      "Do you want to continue? [Y/n]":
      - "Y"

  - name: install python package manager
    apt:
      name: python3-pip

  - name: install python sdk
    become_user: root
    pip:
      name:
      - docker
      - docker-compose
