# Install python and docker
- name: Install Python and Docker
  hosts: all
  remote_user: root
  become: true

  tasks:

  - name: install python package manager
    apt:
      name: python3-pip
    expect:
      command: apt
      responses:
        "Do you want to continue? [Y/n]":
        - "Y"

  - name: install python sdk
    become_user: root
    pip:
      name:
      - docker
      - docker-compose
