# Install python and docker

- name: install python package manager
  apt:
    name: python3-pip

- name: install python sdk
  become_user: "{{ ansible_env.SUDO_USER }}"
  pip:
    name:
    - docker
    - docker-compose
