- name: Swarm Mode
  hosts: all
  remote_user: root
  become: true

  tasks:
  - name: Init Swarm Mode
    community.docker.docker_swarm:
      advertise_addr: 202.10.41.137
      state: present

  - name: Get info on Docker Swarm
    community.docker.docker_swarm_info:
    ignore_errors: true
    register: result
