- name: Create Kasoari Database
  hosts: all
  remote_user: root
  become: true

  tasks:
  - name: Create Volume For Database
    ansible.builtin.command:
      cmd: docker volume create kasoari-mariadb

  - name: Creating Database
    args:
      chdir: "{{ compose_dir }}"
    ansible.builtin.command:
      cmd: docker stack deploy -f "{{ compose_file }}" -f "{{ compose_file_env }}" up -d
